/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package replicamanager;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Oscar Montes
 */
public class ReplicaManagerApp extends javax.swing.JFrame {

    /**
     * Creates new form ReplicaManagerApp
     */
     ConnectionControl adminBDOrigen = ConnectionControl.getInstanceSQLServer();
     ConnectionControl adminBDC1 = ConnectionControl.getInstanceMySQLCompany();
     ConnectionControl adminBDc2 = ConnectionControl.getInstanceMySQLCompany2();

     ControlReplicas control = new ControlReplicas(adminBDOrigen);
        
        
    public ReplicaManagerApp() {
        initComponents();
        
       
        control.agregarReplica(adminBDC1);
        control.agregarReplica(adminBDc2);
        ControlReplicasHilo hilo = new ControlReplicasHilo(control);
        adminBDc2.setEstado(false);
        new Thread(hilo).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        BTNActivar = new javax.swing.JButton();
        BTNPausar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNActivar.setText("Activar");
        BTNActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActivarActionPerformed(evt);
            }
        });

        BTNPausar.setText("Pausar");
        BTNPausar.setEnabled(false);
        BTNPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPausarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(BTNActivar)
                .addGap(92, 92, 92)
                .addComponent(BTNPausar)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNActivar)
                    .addComponent(BTNPausar))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void BTNActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActivarActionPerformed
         try {
             control.despausarReplica(adminBDc2);
         } catch (SQLException ex) {
             Logger.getLogger(ReplicaManagerApp.class.getName()).log(Level.SEVERE, null, ex);
         }
     BTNActivar.setEnabled(false);
     BTNPausar.setEnabled(true);
    }//GEN-LAST:event_BTNActivarActionPerformed

    private void BTNPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPausarActionPerformed
        // TODO add your handling code here:
         adminBDc2.setEstado(false);
        BTNPausar.setEnabled(false);
       BTNActivar.setEnabled(true);
    }//GEN-LAST:event_BTNPausarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplicaManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplicaManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplicaManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplicaManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReplicaManagerApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton BTNActivar;
    javax.swing.JButton BTNPausar;
    // End of variables declaration//GEN-END:variables
}
